name: Scraping Workflow

on:
  push:
    branches:
      - main  # Ejecuta el workflow en cada push a la rama main
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  scrape_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install pandas

    - name: Run scraping script
      run: python Actividad1.ipynb

